# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4472055bdab3b3a5dffdef57f3cdaf131d8902097605b8cdcfe126350a05b2a07be379b44be5b01669281f98f407a8b50932985f1e5765af49011fd05787ac7c

test:
  secret_key_base: d0d7cccba551600de085760fed7b4c729e7959874232e47c380930c9f37cbaf4a80c1e1276b0feb9ac0a29ea3cd224cbc4cb2ddbbd2dfa4c2c8500eece9f3e8b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
